create table if not exists profiles (
  id uuid primary key,
  display_name text not null,
  xp integer not null default 0,
  level integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists artifacts (
  id text primary key,
  name text not null,
  category text not null,
  region text not null,
  period text,
  description text not null,
  model_url text
);

create table if not exists player_progress (
  id bigint generated by default as identity primary key,
  player_id uuid,
  location_id text not null,
  mission_id text,
  progress jsonb not null default '{}'::jsonb,
  completed boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists player_artifacts (
  player_id uuid,
  artifact_id text references artifacts(id),
  discovered_at timestamptz not null default now(),
  primary key (player_id, artifact_id)
);
